[workspace]
members = [
    "crates/rr-core", "crates/rr-mcp",
    "crates/rr-report",
    "crates/rr-scip"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/TonyMarkham/refactor-radar"

[workspace.dependencies]
clap                            = { version = "4.6.1", features = ["derive"] }
error-location                  = { version = "0.1.0" }
protobuf                        = { version = "3.7.2" }
protobuf-json-mapping           = { version = "3.7.2" }
rmcp                            = { version = "1.7.0", default-features = false, features = ["server", "macros", "schemars", "transport-io"] }
schemars                        = { version = "1.2.1", features = ["derive"] }
# Submodule version adds: SingleLineRange, MultiLineRange, Occurrence.typed_range, and Occurrence.typed_enclosing_range
# scip                            = { version = "0.8.1" }
serde                           = { version = "1.0.228", features = ["derive"] }
serde_json                      = { version = "1.0.150" }
soul-attributes                 = { version = "0.1.1" }
tempfile                        = { version = "3.27.0" }
thiserror                       = { version = "2.0.18" }
tokio                           = { version = "1.52.3", features = ["macros", "process", "rt-multi-thread"] }

rr-core                         = { path = "crates/rr-core" }
rr-scip                         = { path = "crates/rr-scip" }
rr-report                       = { path = "crates/rr-report" }

scip                            = { path = "submodules/scip/bindings/rust" }

[workspace.lints.clippy]
unwrap_used     = "deny"
expect_used     = "deny"
panic           = "deny"

[workspace.lints.rust]
unused_must_use = "deny"
