[package]
name = "rr-mcp"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
async-trait    = { workspace = true }
clap           = { workspace = true }
error-location = { workspace = true }
futures        = { workspace = true }
rmcp           = { workspace = true }
schemars       = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
sha2           = { workspace = true }
tempfile       = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }

rr-core        = { workspace = true }
rr-report      = { workspace = true }
rr-scip        = { workspace = true }

[dev-dependencies]
protobuf       = { workspace = true }
rmcp           = { workspace = true, features = ["client"] }
scip           = { workspace = true }

[lints]
workspace = true
