use rmcp::{
    ClientHandler, ErrorData as ProtocolError, RoleClient,
    model::{
        ClientCapabilities, ClientInfo, CreateMessageRequestParams, CreateMessageResult,
        Implementation, SamplingMessage,
    },
    service::RequestContext,
};

use std::sync::{
    Arc,
    atomic::{AtomicUsize, Ordering},
};

#[derive(Clone)]
pub struct SamplingTestClient {
    capabilities: ClientCapabilities,
    sampling_calls: Arc<AtomicUsize>,
}

impl SamplingTestClient {
    pub fn with_sampling() -> Self {
        Self {
            capabilities: ClientCapabilities::builder().enable_sampling().build(),
            sampling_calls: Arc::new(AtomicUsize::new(0)),
        }
    }

    pub fn without_sampling() -> Self {
        Self {
            capabilities: ClientCapabilities::default(),
            sampling_calls: Arc::new(AtomicUsize::new(0)),
        }
    }

    pub fn sampling_call_count(&self) -> usize {
        self.sampling_calls.load(Ordering::SeqCst)
    }
}

impl ClientHandler for SamplingTestClient {
    async fn create_message(
        &self,
        _params: CreateMessageRequestParams,
        _context: RequestContext<RoleClient>,
    ) -> Result<CreateMessageResult, ProtocolError> {
        self.sampling_calls.fetch_add(1, Ordering::SeqCst);
        let json = serde_json::json!({
            "summary": "generated by protocol test client",
            "five_w": {
                "who": "unknown",
                "what": "generated from MCP sampling request",
                "when": "unknown",
                "where": "src/lib.rs",
                "why": "unknown",
                "how": "deterministic integration test response"
            },
            "unknowns": ["runtime behavior is unknown from SCIP"]
        });

        Ok(CreateMessageResult::new(
            SamplingMessage::assistant_text(json.to_string()),
            "protocol-test-model".to_owned(),
        )
        .with_stop_reason(CreateMessageResult::STOP_REASON_END_TURN))
    }

    fn get_info(&self) -> ClientInfo {
        ClientInfo::new(
            self.capabilities.clone(),
            Implementation::new("rr-mcp-protocol-test-client", "0.0.0"),
        )
    }
}
